name: tests

on:
  workflow_dispatch:


jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Set up Ruby
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: 2.6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # 6.4.0
        with:
          go-version: '^1.17'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          poetry install
          poetry run pip install -r requirements_dev.txt
          gem install github-linguist -v 7.15
          wget https://github.com/fossology/fossology/releases/download/4.5.1/FOSSology-4.5.1-ubuntu-noble.tar.gz
          tar -xzf FOSSology-4.5.1-ubuntu-noble.tar.gz
          sudo apt-get update -y
          sudo apt-get -y install ./packages/fossology-common_4.5.1-1_amd64.deb \
                                  ./packages/fossology-nomos_4.5.1-1_amd64.deb
          sudo apt-get install cloc

      - name: Install requirements
        run: |
          mkdir exec
          cd exec
          go install github.com/boyter/scc@latest
          cd $GITHUB_WORKSPACE/exec/
          git clone https://github.com/nexB/scancode-toolkit.git
          cd scancode-toolkit
          ./scancode --help
          cd $GITHUB_WORKSPACE/exec/
          wget https://github.com/crossminer/crossJadolint/releases/download/Pre-releasev2/jadolint.jar
          cd $GITHUB_WORKSPACE/

      - name: Lint with flake8
        run: |
          poetry run flake8 --exclude=exec,src

      - name: Tests and Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd tests
          poetry run coverage run --source=graal run_tests.py
      - name: Coveralls
        uses: coverallsapp/github-action@643bc377ffa44ace6394b2b5d0d3950076de9f63 # v2.3.0
        with:
          coverage-reporter-version: "v0.6.9"
          flag-name: run ${{ join(matrix.*, ' - ') }}
          parallel: true
